version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/html/sandbox

  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

