version: '3'

services:
  app:
    build: .
    command: bin/cake server -H 0.0.0.0
    volumes:
      - ./app:/var/www/app
    ports:
      - 8765:8765
    depends_on:
      - db

  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sandbox
      MYSQL_ROOT_PASSWORD: password
